### ISSUE TITLE
Unable to Delete Saves

### ISSUE THREAD

**Issue by Sonamyfan875** [mvviner/EgyptOldKingdomMapHack#1]
No matter how hard I fucking try to keep 30+ saves from clogging my save window, because of this damn program, any time I reactivate it, they pop back up. How the fuck do I delete these damn things with the program on?! Anytime I turn it back on, all the fucking trash saves come back!

**Comment by mvviner** [comment]
The game stores save files are in: %UserProfile%\AppData\LocalLow\Clarus Victoria\Egypt Old-Kingdom\saves
The utility stores backup files in: %UserProfile%\AppData\LocalLow\Clarus Victoria\Egypt Old-Kingdom\saves\backup
%UserProfile% is typically C:\Users\user_name\
You need to remove files from both folders. Or just completely remove the backup folder.
